@url=http://localhost:8080
### GET Orders
GET {{url}}/order

### GET Specific order
GET {{url}}/order/1

### POST Create order
POST {{url}}/order/
Content-Type: application/json
Accept: application/json

{
    "customerId": "Order 1",
    "orderId": "order1",
    "orderStatus": "Initial1",
    "baristaId": "barista1",
    "orderItems": [
        {
            "itemId": "item4",
            "quantity": 1,
            "price": 10,
            "itemName": "Item 4"
        },
        {
            "itemId": "item5",
            "quantity": 1,
            "price": 10,
            "itemName": "Item 5"
        }
    ]
}