mongodb:
  enabled: true
  host: mongodb:27017
  protocol: mongodb
  credentials: mongoadmin:secret
  options: retryWrites=true&authSource=admin
  database: order
management:
  otlp:
    logging:
      export:
        enabled: true
      endpoint: http://loki:4317/otlp
    metrics:
      export:
        enabled: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"