mongodb:
  enabled: true
  host: localhost:27017
  protocol: mongodb
  credentials: mongoadmin:secret
  options: retryWrites=true&authSource=admin
  database: order
kafka:
  enabled: true
  bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
  producer:
    client-id: cafe-order-producer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  otlp:
    logging:
      export:
        enabled: true
      endpoint: http://localhost:4317/otlp
    metrics:
      export:
        enabled: true
logging:
  level:
    org.apache.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"