spring:
  application:
    name: cafe-order
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    producer:
      client-id: cafe-order-producer
      bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
      properties:
        enable:
          idempotence: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mongodb:
  host: 127.0.0.1:27017
  protocol: mongodb
  credentials: mongoadmin:secret
  options: retryWrites=true&authSource=admin
  database: order
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  defaults:
    metrics:
      export:
        enabled: true
  health:
    mongo:
      enabled: true
  info:
    build:
      enabled: true
    java:
      enabled: true
  tracing:
    enabled: true
  otlp:
    logging:
      export:
        enabled: true
      endpoint: http://127.0.0.1:4317/otlp
    metrics:
      export:
        enabled: true
    
  
