kafka:
  enabled: true
  bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
  producer:
    client-id: cafe-order-producer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    org.apache.kafka: INFO