spring:
  application:
    name: cafe-order
management:
  server:
    port: 1080
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  defaults:
    metrics:
      export:
        enabled: true
  health:
    mongo:
      enabled: true
  info:
    build:
      enabled: true
    java:
      enabled: true
  tracing:
    enabled: true
  
