spring:
  application:
    name: cafe-order
mongodb:
  host: localhost
  port: 27017
  database: order
  collection: orders
  username: mongoadmin
  password: secret
kafka:
  bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  security-protocol: PLAINTEXT
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer