mongodb:
  host: mongodb:27017
  protocol: mongodb
  credentials: mongoadmin:secret
  options: retryWrites=true&authSource=admin
  database: order
spring:
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: kafka1:9092,kafka2:9093,kafka3:9094
    producer:
      client-id: cafe-order-producer
      properties:
        enable:
          idempotence: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  otlp:
    logging:
      export:
        enabled: true
      endpoint: http://loki:4317/otlp
    metrics:
      export:
        enabled: true
logging:
  level:
    org.apache.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"