logging:
  level:
    org.apache.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
management:
  otlp:
    logging:
      export:
        enabled: true
      endpoint: http://localhost:4317/otlp
    metrics:
      export:
        enabled: true
