spring:
  application:
    name: cafe-order
  kafka:
    producer:
      properties:
        enable:
          idempotence: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mongodb:
  host: localhost
  port: 27017
  database: order
  collection: orders
  username: mongoadmin
  password: secret
