spring:
  application:
    name: cafe-order
  kafka:
    security:
      protocol: SSL
    ssl:
      key-store-location: file:/project/sbcp.p12
      key-store-password: sbs123
      key-store-type: PKCS12
      trust-store-location: file:/project/sbcp.p12
      trust-store-password: sbs123
      trust-store-type: PKCS12
    producer:
      security:
        protocol: SSL
      properties:
        enable:
          idempotence: false
      ssl:
        key-store-location: file:/project/sbcp.p12
        key-store-password: sbs123
        key-store-type: PKCS12
        trust-store-location: file:/project/sbcp.p12
        trust-store-password: sbs123
        trust-store-type: PKCS12
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mongodb:
  host: localhost
  port: 27017
  database: order
  collection: orders
  username: mongoadmin
  password: secret