kafka:
  enabled: true
  bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  producer:
    client-id: cafe-order-producer
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    org.apache.kafka: INFO