apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafe-order-app
  namespace: sbcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafe-order
  template:
    metadata:
      labels:
        app: cafe-order
    spec:
      containers:
        - name: cafe-order
          image: 461232396433.dkr.ecr.eu-west-1.amazonaws.com/test/cafe_order:1.0 
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APP_HEALTHCHECK
              value: "false"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP_SERVERS
                  name: kafka-config
            - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
              value: "org.apache.kafka.common.serialization.StringSerializer"
            - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
              value: "org.apache.kafka.common.serialization.StringSerializer"
            - name: SPRING_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_HOST
                  name: environment-config
            - name: SPRING_MONGODB_OPTIONS
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_OPTIONS
                  name: environment-config
            - name: SPRING_MONGODB_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_PROTOCOL
                  name: environment-config
            - name: SPRING_MONGODB_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_CREDENTIALS
                  name: environment-config
      serviceAccount: sbcp-busybox-sa
      serviceAccountName: sbcp-busybox-sa
