global:
  scrape_interval:     15s
  evaluation_interval: 15s

otlp:
  keep_identifying_resource_attributes: true
  translation_strategy: 'UnderscoreEscapingWithSuffixes'
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - container.name

scrape_configs:
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]